package com.es.practiarmar.repository;

import com.es.practiarmar.model.Customer;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
* Generated by Spring Data Generator on 27/07/2025
*/
@Repository
public interface CustomerRepository extends JpaRepository<Customer, Long> {
    @Query("SELECT c FROM customer c WHERE c.id = :id AND c.isDeleted = false")
    Optional<Customer> findByIdAndDeletedFalse(@Param("id") Long id);
    @Query("SELECT c FROM customer c WHERE c.isDeleted = false")
    List<Customer> findAllByDeletedIsFalse();
    @Query("SELECT CASE WHEN COUNT(c) > 0 THEN TRUE ELSE FALSE END " +
            "FROM customer c WHERE c.nombre = :name AND c.isDeleted = false")
    boolean existsByNombreAndDeletedFalse(@Param("name") String name);
    @Query("SELECT CASE WHEN COUNT(c) > 0 THEN TRUE ELSE FALSE END " +
            "FROM customer c WHERE c.email = :email AND c.isDeleted = false")
    boolean existsByEmailAndIsDeletedFalse(@Param("email") String email);
    @Query("SELECT CASE WHEN COUNT(c) > 0 THEN TRUE ELSE FALSE END " +
            "FROM customer c WHERE c.nombre = :name AND c.id <> :id")
    boolean existsByNombreAndIdNot(@Param("name") String name,@Param("id") long id);
    @Query("SELECT c.email FROM customer c WHERE c.recibirNotificaciones = true AND c.isDeleted = false ")
    List<String> fetchEmailCustomersNotification();
}
