package com.es.practiarmar.repository;

import com.es.practiarmar.model.Employee;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
* Generated by Spring Data Generator on 27/07/2025
*/
@Repository
public interface EmployeeRepository extends JpaRepository<Employee, Long> {

    @Query("SELECT e FROM employee e WHERE e.isDeleted = false")
    List<Employee> findAllByDeletedIsFalse();
    @Query("SELECT CASE WHEN COUNT(e) > 0 THEN TRUE ELSE FALSE END FROM employee e WHERE e.username=:username AND e.isDeleted=false")
    boolean existsByUsernameAndDeletedFalse(@Param("username") String username);
    @Query("SELECT e FROM employee e WHERE e.username=:username AND e.isDeleted=false")
    Optional<Employee> findByUsernameAndDeletedFalse(@Param("username") String username);
    @Query("SELECT CASE WHEN COUNT(e) > 0 THEN TRUE ELSE FALSE END FROM employee e WHERE e.username=:username AND e.id<>:id")
    boolean existsByUsernameAndIdNot(@Param("username") String username, @Param("id") Long id);
    @Query("SELECT e FROM employee e WHERE e.id= :id AND e.isDeleted=false")
    Optional<Employee> findByIdAndDeletedFalse(@Param("id") Long id);
}
