package com.es.practiarmar.repository;

import com.es.practiarmar.model.Tool;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 27/07/2025
*/
@Repository
public interface ToolRepository extends JpaRepository<Tool, Long> {

}
